### ISSUE TITLE
NameError (uninitialized class variable @@context_obj in RedmineDropbox::AttachmentPatch::ClassMethods): app/models/attachment.rb:252:in `attach_files'

### ISSUE THREAD

**Issue by iaminawe** [alexbevi/redmine_dropbox_attachments#23]
I get this error int he logs when trying to save a user avatar using this plugin enabled in conjunction with the Redmine People plugin http://www.redminecrm.com/projects/people/pages/1

If I move the dropbox module out of the folder then the error goes away and avatars can be saved correctly again. Please let me know if you may have any idea how to fix this is as both are very useful plugins. Thanks

**Comment by alexbevi** [comment]
Does the plugin work when the people plugin is removed?

**Comment by alexbevi** [comment]
Closing this as it will be addressed along with #24
