### ISSUE TITLE
Redmine 3.x?

### ISSUE THREAD

**Issue by rchady** [alexbevi/redmine_dropbox_attachments#25]
Curious if you have support in the works for Redmine 3.x?

**Comment by yukoff** [comment]
It should work, actually - at least it was tested on 3.2 and 3.3

**Comment by yukoff** [comment]
Hi @rchady,

Do you have any issues with this plugin? Should we close this issue?

**Comment by rchady** [comment]
Well, I found the reason for the exact issue I was having.  Seems that in the master branch they have a whole pile of changes coming that are not compatible.  I ran in to other issues though and ended up putting this on hold.  I will close this until I have actual useful information for you though.
